hakonharnes/img-clip.nvim

- README.md
- lua/img-clip/clipboard.lua
- lua/img-clip/config.lua
- lua/img-clip/init.lua
- lua/img-clip/markup.lua
- tests/config_spec.lua
- tests/init_spec.lua
Embeds image as Base64 rather than saving the file and referencing it in the markup. Only works for Markdown currently, as LaTeX and Typst do not support embedding images as Base64.
> feat: embed image as base64

- README.md
- lua/img-clip/config.lua
- lua/img-clip/init.lua
- tests/config_spec.lua
- tests/init_spec.lua
Closes #9.
Added a `max_base64_size` option which defines the max size of the Base64 string in KB. Keep in mind embedding as Base64 will increase the file size with 33%, and 10KB of Base64 equals 10 240 characters.
> feat: base64 limit

- lua/img-clip/clipboard.lua
- lua/img-clip/config.lua
- lua/img-clip/util.lua
- tests/clipboard_spec.lua
- tests/util_spec.lua
Closes #13.
Issue occured because `Get-Clipboard -Format Image` does not work in some Powershell versions, see: 
```
Get-Clipboard : A parameter cannot be found that matches parameter name 'Format'
```
Another issue was the default shell used in Neovim was changed from the default `cmd.exe` to `pwsh` (obtained from `:set shell?`), which caused parsing issues when attempting to get the clipboard. 
- Replaced the `Get-Clipboard` command to equivalent `.NET` command. 
- Format the powershell commands correctly by handled different `shell` values.
The Powershell commands are handled as follows: 
1. If the `shell` is `powershell` or `pwsh`, then execute the command directly. 
2. If the client uses WSL, wrap the command in `powershell.exe -Command 'command "path/to/file.png"'`
3. Otherwise …
> fix: clipboard not working on windows

- README.md
- lua/img-clip/drag_and_drop.lua
- plugin/img-clip.lua
- tests/drag_and_drop_spec.lua
- vimdoc.md
Converts streaming pastes to non-streaming pastes, which caused multiple `vim.paste` calls in WSL. Also moved some of the checks to `plugin/img-clip.lua` to only do this conversion when it's really necessary.
> fix: wsl drag and drop

- README.md
- lua/img-clip/config.lua
- lua/img-clip/fs.lua
- lua/img-clip/markup.lua
- tests/fs_spec.lua
- vimdoc.md
Closes #21.
- Added the `relpath` function for resolving relative paths. 
- Added the `relative_template_path` option.
- Updated docs to reflect changes.
> fix: relative to current file markdown

- lua/img-clip/init.lua
Adds base64 support for more markdown-like file types: 
- `md` 
- `wiki`
- `vimwiki`
> feat(base64): support more file types

- lua/img-clip/util.lua
The startup of powershell.exe is unbearably slow without the -NoProfile option. Because we don't need the profiles of powershell.exe, add this option will greatly improve the experience.
Add -NoProfile option to powershell.exe
> fix: add -NoProfile to powershell.exe options to speedup

- README.md
- lua/img-clip/config.lua
- lua/img-clip/markup.lua
- tests/config_spec.lua
- tests/markup_spec.lua
- vimdoc.md
Closes #26.
Passes the following args to the template function: 
```lua
local template_args = {
file_path = file_path,
file_name = file_name,
file_name_no_ext = file_name_no_ext,
cursor = "$CURSOR",
label = label,
}
```
- Added a test which uses all of the placeholders.
- Updated readme and vimdoc
> feat: arguments in template function

- lua/img-clip/drag_and_drop.lua
Remove temporary variables in `drag_and_drop.lua` to get it coherent with the rest of the code base.
> refactor: remove redundant variables

- README.md
- lua/img-clip/config.lua
- plugin/img-clip.lua
- Added the `ImgClipConfig` command which prints the current configuration, including the path to the `.img-clip.lua` file if applicable. 
- Updated docs.
> feat: config command

- lua/img-clip/paste.lua
Closes #47.
- Properly calculate the base64 size in KB
- Add a warning message when Base64 size exceeds the `max_base64_size` set in the config
> fix: add base64 length warning

- lua/img-clip/markup.lua
- lua/img-clip/paste.lua
Closes #52. 
- Added a `insert_base64_markup` method for inserting Base64 markup. It was previously treated as a file path, causing issues.
> fix: handle base64 separately from file path

- lua/img-clip/markup.lua
- lua/img-clip/paste.lua
- tests/markup_spec.lua
- Refactored the markup logic such that the `insert_markup` method now accepts an optional `is_file_path` argument
- Created a `get_template` function for getting the correct template, differentiating between the processing that needs to be done for file paths and other inputs like Base64 or URLs.
> refactor: simplify markup logic

- lua/img-clip/clipboard.lua
- lua/img-clip/fs.lua
- Properly escapes special characters in the `process_cmd` before executing it. This allows commands like `convert - -resize 10% -` to execute correctly.
> fix: escape special characters in `process_cmd`

- README.md
- lua/img-clip/config.lua
- lua/img-clip/paste.lua
- plugin/img-clip.lua
- tests/config_spec.lua
- vimdoc.md
- Added a `config.drag_and_drop` option which allows the plugin to know if a paste was invoked as a drag and drop action 
- When getting options using the `get_opt` function, the code will now first check if we're in drag and drop mode. If we are, we prepend "drag_and_drop." to the key and recursively check if we can find it. If not, we use the default options. This allows the user to override any option under the `drag_and_drop` options
- Moved `copy_images` and `download_images` outside of drag and drop, as these are also relevant as "normal" options now that the API  is more powerfull
> refactor: drag and drop options

- lua/img-clip/fs.lua
- lua/img-clip/paste.lua
- Checks if the user has added a file extension to the file path. If they have, don't add the .png file extension
> fix: only add file extension if its missing

- lua/img-clip/util.lua
- tests/util_spec.lua
Closes #64. User has likely set Fish as their default shell in Neovim.
- Use `sh -c` to ensure the shell used for execution is POSIX compliant
> fix: use sh -c to execute commands

- README.md
- lua/img-clip/config.lua
- vimdoc.md
> feat: support vimwiki

- lua/img-clip/health.lua
Closes #73 
- Change the order of if statements so wayland is checked before x11. This has to be done because the `DISPLAY` environment variable is set in both Wayland and X11. This way, Wayland sessions are properly detected.
> fix: check wayland before x11

- lua/img-clip/paste.lua
Closes #80.
- Use relative path for drag and drop if `use_absolute_path` is `false`
> fix: relative path drag and drop

- lua/img-clip/config.lua
- plugin/img-clip.lua
Closes #98 
- Moved `M.setup` call back to config file because it caused issues with vim-plug.
> refactor: move setup function back to config.lua

- lua/img-clip/paste.lua
#106 
This will use the existing extension when copying a file if one exists.
> Don't replace extension when copying a file

- README.md
I have added example configuration to integrate Snacks.nvim picker with img-clip.nvim to `README.md`
> docs: add example configuration for Snacks.nvim picker

- README.md
otherwise, you get empty .png files.
> stating `pngpaste` is required on macOS

- lua/img-clip/markup.lua
Closes #135. 
Handle empty templates explicitly by returning early.
> fix: handle empty templates
